### ISSUE TITLE
The `jlpm bootstrap` looks not to be working.

### ISSUE THREAD

**Issue by i-aki-y** [jupyter-lsp/jupyterlab-lsp#1017]
## Description

I tried to build jupyterlab-lsp according to CONTRIBUTING.md but could not because the `jlpm bootstrap` did not complete successfully.

I have checked them individually and found the following scripts have errors.
- jlpm deduplicate
- lerna bootstrap

Note, running only `jlpm build`  completed without error.

## Reproduce

```
# git clone https://github.com/jupyter-lsp/jupyterlab-lsp.git
# cd jupyterlab-lsp
# conda env update -n jupyterlab-lsp --file binder/environment.yml
# conda activate jupyterlab-lsp
# bash binder/postBuild
+ jlpm bootstrap
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

# jlpm
# bash binder/postBuild
+ jlpm bootstrap
[1] ➤ YN0000: ┌ Project validation
[1] ➤ YN0057: │ root-workspace-0b6124: 'nohoist' is deprecated, please use 'installConfig.hoistingLimits' instead
[1] ➤ YN0000: └ Completed
[1] ➤ YN0000: ┌ Resolution step
SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at module.exports.exports.default (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at parseYarnLock (/jupyterlab-lsp/node_modules/yarn-deduplicate/dist/index.js:7:42)
    at fixDuplicates (/jupyterlab-lsp/node_modules/yarn-deduplicate/dist/index.js:123:18)
    at Object.<anonymous> (/jupyterlab-lsp/node_modules/yarn-deduplicate/dist/cli.js:52:60)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
[1] ➤ YN0002: │ @jupyter-lsp/jupyterlab-lsp-example-extractor@workspace:packages/_example-extractor doesn't provide @codemirror/state (pb2869), requested by @jupyter-lsp/jupyterlab-lsp
[1] ➤ YN0002: │ @jupyter-lsp/jupyterlab-lsp-example-extractor@workspace:packages/_example-extractor doesn't provide @codemirror/view (pad4db), requested by @jupyter-lsp/jupyterlab-lsp
[1] ➤ YN0002: │ @jupyter-lsp/jupyterlab-lsp-metapackage@workspace:packages/metapackage doesn't provide @codemirror/state (p09a35), requested by @jupyter-lsp/jupyterlab-lsp
[1] ➤ YN0002: │ @jupyter-lsp/jupyterlab-lsp-metapackage@workspace:packages/metapackage doesn't provide @codemirror/view (p49198), requested by @jupyter-lsp/jupyterlab-lsp
[1] ➤ YN0002: │ @jupyter-lsp/jupyterlab-lsp@workspace:packages/jupyterlab-lsp doesn't provide @rjsf/utils (p61ef3), requested by @rjsf/validator-ajv8
[1] ➤ YN0002: │ @jupyter-lsp/jupyterlab-lsp@workspace:packages/jupyterlab-lsp [31461] doesn't provide @rjsf/utils (p3362a), requested by @rjsf/validator-ajv8
[1] ➤ YN0002: │ @jupyterlab/services@npm:7.0.5 doesn't provide react (p4d970), requested by @jupyterlab/settingregistry
[1] ➤ YN0002: │ @jupyterlab/services@npm:7.0.6 doesn't provide react (p142a3), requested by @jupyterlab/settingregistry
[1] ➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide webpack (p227f7), requested by source-map-loader
[1] ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
[1] ➤ YN0000: └ Completed in 0s 381ms
[1] ➤ YN0000: ┌ Fetch step
[1] ➤ YN0000: └ Completed in 0s 412ms
[1] ➤ YN0000: ┌ Link step
[1] ➤ YN0000: └ Completed in 0s 608ms
[1] ➤ YN0000: Done with warnings in 1s 505ms
Job [1], 'jlpm' has ended
```

Run individual command:
```
# jlpm deduplicate
SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
    at Parser.unexpected (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:5064:11)
    at Parser.parse (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:5193:14)
    at parse (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:5262:17)
    at module.exports.exports.default (/jupyterlab-lsp/node_modules/@yarnpkg/lockfile/index.js:4835:96)
    at parseYarnLock (/jupyterlab-lsp/node_modules/yarn-deduplicate/dist/index.js:7:42)
    at fixDuplicates (/jupyterlab-lsp/node_modules/yarn-deduplicate/dist/index.js:123:18)
    at Object.<anonymous> (/jupyterlab-lsp/node_modules/yarn-deduplicate/dist/cli.js:52:60)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

```

```
# jlpm lerna bootstrap
lerna notice cli v6.5.1
lerna info versioning independent
lerna info bootstrap root only
Unknown Syntax Error: Unsupported option name ("--mutex").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'jupyterlab-lsp'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'jupyterlab-lsp'
```

## Expected behavior

The command (`jlpm bootstrap`) should be completed without error.

## Context

I confirmed in this docker image
```
docker pull continuumio/miniconda3
docker run -i -t continuumio/miniconda3 /bin/bash
```

Just after the `conda activate jupyterlab-lsp`: 

```
# jlpm --version
3.5.0
# node --version
v18.15.0
# pip list | grep jupyter
jupyter_client                8.6.0
jupyter_core                  5.5.0
jupyter-events                0.9.0
jupyter-lsp                   2.2.0
jupyter_server                2.10.1
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.9
jupyterlab-pygments           0.2.2
jupyterlab-robotmode          0.3.1
jupyterlab_server             2.25.2
jupyterlab-widgets            3.0.9
```

<details><summary>Required: installed server extensions</summary>
<pre>
Paste the output from running `jupyter server extension list` (JupyterLab >= 3)
or `jupyter serverextension list` (JupyterLab < 3) from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
Paste the output from running `jupyter labextension list` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by krassowski** [comment]
Thank you for the report, https://github.com/jupyter-lsp/jupyterlab-lsp/pull/1021 should address this.
