### ISSUE TITLE
Broken Greek letters completion for julia language server

### ISSUE THREAD

**Issue by PhyX-Meow** [jupyter-lsp/jupyterlab-lsp#704]
## Description

Completion for Greek letters for julia notebook currently cannot work:

![bad](https://user-images.githubusercontent.com/17513581/139574591-961eeead-2acc-4566-83d8-5e9cfad8b022.gif)

If lsp is not loaded, completions from kernel works well, sorry but I cannot capture a gif for it.

## Expected behavior

Gives a unicode letter as in repl or vscode's jupyter extension:

![good1](https://user-images.githubusercontent.com/17513581/139574723-8efb4038-48fa-45c5-b162-4ba6c0340a97.gif)
![good2](https://user-images.githubusercontent.com/17513581/139574724-f961ee97-1024-4dfb-93d2-125463cda2f9.gif)

## Reproduce

Type `\alpha` , press `<Tab>`, press `<Enter>`

## Context

- Operating System and version: Archlinux
- Browser and version: Microsoft Edge Beta
- JupyterLab version: 3.2.1

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: /home/wuli/.jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.5.0 OK
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.2.1 OK
    jupyterlab_code_formatter enabled
    - Validating jupyterlab_code_formatter...
      jupyterlab_code_formatter 1.4.10 OK
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.33.0 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    nbdime enabled
    - Validating nbdime...
      nbdime 3.1.0 OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.2.1
/home/wuli/.local/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.0 enabled OK
        @telamonian/theme-darcula v3.1.1 enabled OK (python, theme-darcula)
        @jupyterlab/git v0.33.0 enabled OK (python, jupyterlab-git)
        @jupyterlab/mathjax3-extension v4.2.2 enabled OK (python, jupyterlab-mathjax3)
        @ryantam626/jupyterlab_code_formatter v1.4.10 enabled OK (python, jupyterlab-code-formatter)
        @krassowski/jupyterlab-lsp v3.9.1 enabled OK (python, jupyterlab-lsp)

Other labextensions (built into JupyterLab)
   app dir: /usr/share/jupyter/lab
        jupyterlab-ihaskell v0.0.14 enabled OK

Disabled extensions:
    @jupyterlab/mathjax2-extension:plugin
</pre>
</details>

**Comment by PhyX-Meow** [comment]
Now....I don't know why, the whole julia language server is not working.
Giving me error like this: 
```
[I 2021-11-05 16:10:20.403 ServerApp] Adapting from protocol version 5.0 (kernel d189d8e5-3278-43b5-8d94-722d2b1c2943) to 5.3 (client).
[W 2021-11-05 16:10:20.410 ServerApp] Got events for closed stream None
[ Info: Received new data from Julia Symbol Server.
┌ Error: get_hover failed to convert Expr
│   exception =
│    TypeError: in Expr, expected Symbol, got a value of type CSTParser.EXPR
│    Stacktrace:
│      [1] Expr
│        @ ./boot.jl:253 [inlined]
│      [2] get_hover(b::StaticLint.Binding, documentation::String, server::LanguageServerInstance)
│        @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:58
│      [3] get_hover(x::CSTParser.EXPR, documentation::String, server::LanguageServerInstance)
│        @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:20
│      [4] textDocument_hover_request(params::LanguageServer.TextDocumentPositionParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
│        @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:6
│      [5] (::LanguageServer.var"#96#97"{typeof(LanguageServer.textDocument_hover_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.TextDocumentPositionParams)
│        @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:252
│      [6] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
│        @ JSONRPC ~/.julia/packages/JSONRPC/yu0G3/src/typed.jl:67
│      [7] run(server::LanguageServerInstance)
│        @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:361
│      [8] runserver(pipe_in::Base.PipeEndpoint, pipe_out::Base.PipeEndpoint, env_path::String, depot_path::String, err_handler::Nothing, symserver_store_path::Nothing)
│        @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/runserver.jl:46
│      [9] runserver()
│        @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/runserver.jl:44
│     [10] top-level scope
│        @ none:1
└ @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:60
ERROR: get_hover failed to convert Expr
Stacktrace:
 [1] get_hover(b::StaticLint.Binding, documentation::String, server::LanguageServerInstance)
   @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:61
 [2] get_hover(x::CSTParser.EXPR, documentation::String, server::LanguageServerInstance)
   @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:20
 [3] textDocument_hover_request(params::LanguageServer.TextDocumentPositionParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
   @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:6
 [4] (::LanguageServer.var"#96#97"{typeof(LanguageServer.textDocument_hover_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.TextDocumentPositionParams)
   @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:252
 [5] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ JSONRPC ~/.julia/packages/JSONRPC/yu0G3/src/typed.jl:67
 [6] run(server::LanguageServerInstance)
   @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:361
 [7] runserver(pipe_in::Base.PipeEndpoint, pipe_out::Base.PipeEndpoint, env_path::String, depot_path::String, err_handler::Nothing, symserver_store_path::Nothing)
   @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/runserver.jl:46
 [8] runserver()
   @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/runserver.jl:44
 [9] top-level scope
   @ none:1

caused by: TypeError: in Expr, expected Symbol, got a value of type CSTParser.EXPR
Stacktrace:
  [1] Expr
    @ ./boot.jl:253 [inlined]
  [2] get_hover(b::StaticLint.Binding, documentation::String, server::LanguageServerInstance)
    @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:58
  [3] get_hover(x::CSTParser.EXPR, documentation::String, server::LanguageServerInstance)
    @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:20
  [4] textDocument_hover_request(params::LanguageServer.TextDocumentPositionParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
    @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/requests/hover.jl:6
  [5] (::LanguageServer.var"#96#97"{typeof(LanguageServer.textDocument_hover_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.TextDocumentPositionParams)
    @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:252
  [6] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ JSONRPC ~/.julia/packages/JSONRPC/yu0G3/src/typed.jl:67
  [7] run(server::LanguageServerInstance)
    @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/languageserverinstance.jl:361
  [8] runserver(pipe_in::Base.PipeEndpoint, pipe_out::Base.PipeEndpoint, env_path::String, depot_path::String, err_handler::Nothing, symserver_store_path::Nothing)
    @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/runserver.jl:46
  [9] runserver()
    @ LanguageServer ~/.julia/packages/LanguageServer/JrIEf/src/runserver.jl:44
 [10] top-level scope
    @ none:1
[E 2021-11-05 16:11:04.542 ServerApp] <LspStdIoWriter(parent=<LanguageServerSession(language_server=julia-language-server, argv=['/usr/sbin/julia', '--project=.', '-e', 'using LanguageServer, LanguageServer.SymbolServer; runserver()', '.'])>)> couldn't write message: Content-Length: 208

    {"jsonrpc":"2.0","id":4,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///home/wuli/.virtual_documents/CodesWSL/Jupyter/JuliaTest.ipynb"},"position":{"line":5,"character":0}}}
    Traceback (most recent call last):
      File "/home/wuli/.local/lib/python3.9/site-packages/jupyter_lsp/stdio.py", line 193, in write
        await convert_yielded(self._write_one(response.encode("utf-8")))
      File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/wuli/.local/lib/python3.9/site-packages/jupyter_lsp/stdio.py", line 201, in _write_one
        self.stream.write(message)
    BrokenPipeError: [Errno 32] 断开的管道
[E 2021-11-05 16:11:06.461 ServerApp] <LspStdIoWriter(parent=<LanguageServerSession(language_server=julia-language-server, argv=['/usr/sbin/julia', '--project=.', '-e', 'using LanguageServer, LanguageServer.SymbolServer; runserver()', '.'])>)> couldn't write message: Content-Length: 208

    {"jsonrpc":"2.0","id":5,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///home/wuli/.virtual_documents/CodesWSL/Jupyter/JuliaTest.ipynb"},"position":{"line":5,"character":0}}}
    Traceback (most recent call last):
      File "/home/wuli/.local/lib/python3.9/site-packages/jupyter_lsp/stdio.py", line 193, in write
        await convert_yielded(self._write_one(response.encode("utf-8")))
      File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/wuli/.local/lib/python3.9/site-packages/jupyter_lsp/stdio.py", line 201, in _write_one
        self.stream.write(message)
    BrokenPipeError: [Errno 32] 断开的管道
^C[I 2021-11-05 16:11:20.313 ServerApp] interrupted
```

**Comment by krassowski** [comment]
Please provide a minimal reproducible example in a separate issue; `ERROR: get_hover failed to convert Expr` suggests that this is an error in the Julia language server, not in `jupyterlab-lsp` extension. It is likely a very specific code fragment that triggers it.

**Comment by PhyX-Meow** [comment]
> Please provide a minimal reproducible example in a separate issue; `ERROR: get_hover failed to convert Expr` suggests that this is an error in the Julia language server, not in `jupyterlab-lsp` extension. It is likely a very specific code fragment that triggers it.

OK, I'll try. But what I concern is BrokenPipeError in later of the log, which seems to occur every time I try to do code completion.

**Comment by PhyX-Meow** [comment]
No, I was wrong, seems I run into some random error, after restart jupyterlab, the errors are gone. But still cannot correctly
completion. Thanks for reply!

**Comment by krassowski** [comment]
`BrokenPipeError` only tells us that the LSP server had an internal error; the traceback tells us what this error is and it definitely is on the Julia language server side.

**Comment by krassowski** [comment]
Thank you for bringing the issue of Greek letters up. I found the cause: both kernel and LSP server return Greek letter suggestions leading to a clash; because we do not handle `textEdit`s yet, the label is inserted (again) instead of the Greek letter.

To fix that we will need to implement handling of `textEdit` property from completion response. This in turn will require refactoring completer API in JupyterLab core to allow multiple start/end points.

I investigated potential workarounds but none can be reliably applied without improving the completer API internals. I hope I can get the necessary changes in between JupyterLab 4.0 release (by the end of the year) so that it can work in the next version.

**Comment by ytdHuang** [comment]
I have this issue too.
Has it been fixed?

**Comment by mjappels** [comment]
FWIW, This also seems to be broken in Python for me. My versions:
```
ipython                   8.7.0
jupyter-lsp               1.5.1
jupyterlab                3.5.2
python-lsp-server         1.7.0
```

Disabling completion in the advanced settings editor and reloading lab seems to restore greek letter completion.
