### ISSUE TITLE
ImportError: DLL load failed while importing ujson

### ISSUE THREAD

**Issue by gG8Fkpxq** [jupyter-lsp/jupyterlab-lsp#934]
Why?
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Mycode\Python\Python311\Lib\site-packages\pylsp\__main__.py", line 15, in <module>
    from .python_lsp import (PythonLSPServer, start_io_lang_server,
  File "C:\Mycode\Python\Python311\Lib\site-packages\pylsp\python_lsp.py", line 9, in <module>
    import ujson as json
ImportError: DLL load failed while importing ujson: 拒绝访问。
```
Jupyter lab:
![image](https://user-images.githubusercontent.com/97328142/234051358-71a6197f-bddb-40f5-8758-c259570b6510.png)

**Comment by krassowski** [comment]
It appears that this is not a jupyterlab-lsp issue, but a problem with a dependency of [python-lsp-server](https://github.com/python-lsp/python-lsp-server) on Windows. As there is no bug in jupyterlab-lsp we cannot help here and I will close the issue, but if you happen to find a solution, please feel welcome to share here to benefit other users :)
