### ISSUE TITLE
NotebookApp Error loading server extension jupyter_lsp

### ISSUE THREAD

**Issue by joernhees** [jupyter-lsp/jupyterlab-lsp#943]
Hi, not entirely sure if this is the right place, but i get the following warning after doing a fresh install of jupyter:

```
[W 18:55:41.620 NotebookApp] Error loading server extension jupyter_lsp
    Traceback (most recent call last):
      File "/Users/joern/.pyenv/versions/3.11.3/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
        func(self)
      File "/Users/joern/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
        nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
        ^^^^^^^^^^^^^
    AttributeError: 'NotebookApp' object has no attribute 'io_loop'
```

Installed like this (on OS X 13.4, brewed pyenv):
```
pyenv install 3.11.3
pyenv global 3.11.3
which pip3
pip3 install -U pip setuptools six wheel virtualenv
pip3 install jupyterlab notebook
```

Any ideas / hints / workarounds?

**Comment by krassowski** [comment]
The old `notebook` server is going away and it seems that we (unintentionally) started to rely on features from new `jupyter-server`. You probably want to disable `jupyter-lsp` for the old server as it is of no use with Jupyter Notebook 6 anyways:

```
jupyter serverextension disable jupyter-lsp
```

Please note **no** space betwen "server" and "extension" (this is the command for old server).

**Comment by joernhees** [comment]
thanks for the super fast answer... still the same though:

```
$ jupyter serverextension disable jupyter-lsp
Disabling: jupyter-lsp
- Writing config: /Users/joern/.jupyter
$ jupyter notebook
...
[W 19:15:32.013 NotebookApp] Error loading server extension jupyter_lsp
    Traceback (most recent call last):
      File "/Users/joern/.pyenv/versions/3.11.3/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
        func(self)
      File "/Users/joern/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
        nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
        ^^^^^^^^^^^^^
    AttributeError: 'NotebookApp' object has no attribute 'io_loop'
...
```

**Comment by krassowski** [comment]
What about?
```
jupyter serverextension disable jupyter_lsp
```

If not, what does

```
jupyter serverextension list
```

show?

**Comment by joernhees** [comment]
ah, didn't spot the `-` vs `_`, that did the trick ❤️ ❤️ ❤️

**Comment by yasirroni** [comment]
In my case, the error changes to `Server error: Forbidden` like in [this SO question](https://stackoverflow.com/questions/75106093/403-forbidden-error-jupyter-server-on-anaconda/77458618#77458618).

Current working solution is to downgrade jupyter-server: `pip install jupyter-server==1.24.0` as explained [here](https://stackoverflow.com/a/77458618/11671779)
